before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm_6
      - darwin_arm64
      - darwin_amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - maintainer: Brandon Wagner
    
    description: |-
      a daemon that shuts down an instance when a spot interruption termination notice 
      is received from the EC2 Instance Metadata Service.
    
    license: Apache 2.0

    dependencies:
      - polkit
    
    formats:
      - apk
      - deb
      - rpm

    contents:
      - src: etc/systemd/nthd.service
        dst: /etc/systemd/system/nthd.service
        file_info:
          mode: 0644

      - src: etc/scripts/postinstall.sh
        dst: /etc/scripts/postinstall.sh
        file_info:
          mode: 0755
      
      - src: etc/scripts/preinstall.sh
        dst: /etc/scripts/preinstall.sh
        file_info:
          mode: 0755

      - src: etc/scripts/postremove.sh
        dst: /etc/scripts/postremove.sh
        file_info:
          mode: 0755

      - src: etc/polkit-1/localauthority/rules.d/10-allow-nthd-poweroff.rules
        dst: /etc/polkit-1/localauthority/rules.d/10-allow-nthd-poweroff.rules
        type: config
        file_info:
          mode: 0644

    scripts:
      preinstall: etc/scripts/preinstall.sh
      postinstall: etc/scripts/postinstall.sh
      postremove: etc/scripts/postremove.sh
